package com.teleteh.xplayer2.data.network

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-implementation known-answer tests for §2.20 (`depth` / `set_depth`) and §2.21 (`stats`).
 *
 * `src/test/resources/pclink_depth_vectors.json` is a verbatim copy of
 * `xplayer-link-server/crates/xpl-proto/test-vectors/depth_vectors.json` — the same bytes the Rust
 * and Swift suites consume, so no implementation can drift without the others noticing. Same
 * arrangement as [PcLinkInputVectorsTest] and the input vectors it drives.
 *
 * **The fixture is duplicated in two repositories on purpose and must be kept in step**: it is
 * generated by the server's `docs/gen_depth_vectors.py`, and a regeneration there is only finished
 * once the copy here is refreshed. [`the fixture is the server's, unmodified`] pins the generator's
 * own description so a copy taken from somewhere else, or edited here to make a test pass, fails
 * loudly rather than quietly diverging.
 *
 * Four sections, and this client owns different amounts of each:
 *
 * * `wire` — the exact newline-JSON of every message. The client→server lines are entirely ours,
 *   byte for byte; the server→client lines are what our parser must accept.
 * * `decode` — what to keep and what to ignore whole. Entirely ours.
 * * `apply` — the server's policy: what a `set_depth` does to its state and what `depth` it answers
 *   with. Informational for a sender, but the acknowledgements are lines our parser reads, and the
 *   clamp is the rule our sliders are shaped by — so both halves are asserted here.
 * * `gate` — when the server sends `depth` and `stats` at all. What it pins for us is the hint in
 *   `hello`, and that `false` says nothing `absent` does not.
 */
class PcLinkDepthVectorsTest {

    private val doc: JSONObject by lazy {
        val text = javaClass.classLoader!!
            .getResourceAsStream("pclink_depth_vectors.json")!!
            .use { it.readBytes().toString(Charsets.UTF_8) }
        JSONObject(text)
    }

    private fun section(name: String): List<JSONObject> = objects(doc.getJSONArray(name))

    private fun objects(array: JSONArray): List<JSONObject> =
        (0 until array.length()).map { array.getJSONObject(it) }

    /** The fixture's `set_depth` object → the request this client would have built. */
    private fun request(m: JSONObject) = PcDepthRequest(
        divergence = if (m.has("divergence")) m.getInt("divergence") else null,
        convergence = if (m.has("convergence")) m.getInt("convergence") else null,
        reset = m.optBoolean("reset", false)
    )

    private fun range(a: JSONArray) = PcDepthRange(a.getInt(0), a.getInt(1))

    /**
     * The fixture's `depth` object, read with `org.json`'s own getters, → the state we expect our
     * parser to produce. Built by hand rather than through the parser under test, so the
     * comparison is between two readings of the same fixture and not between the parser and itself.
     */
    private fun depth(m: JSONObject): PcDepthState {
        val defaults = m.getJSONObject("defaults")
        val limits = m.getJSONObject("limits")
        return PcDepthState(
            setting = m.getString("setting"),
            active = m.getBoolean("active"),
            divergence = m.getInt("divergence"),
            convergence = m.getInt("convergence"),
            defaults = PcDepthValues(defaults.getInt("divergence"), defaults.getInt("convergence")),
            limits = PcDepthLimits(
                divergence = range(limits.getJSONArray("divergence")),
                convergence = range(limits.getJSONArray("convergence"))
            )
        )
    }

    private fun stats(m: JSONObject) = PcStreamStats(
        captureFps = m.getDouble("capture_fps"),
        encodeFps = m.getDouble("encode_fps"),
        encodeMs = m.getDouble("encode_ms"),
        wireMbps = m.getDouble("wire_mbps")
    )

    private fun expected(m: JSONObject): Any = when (val t = m.getString("type")) {
        "depth" -> depth(m)
        "stats" -> stats(m)
        else -> throw AssertionError("unexpected message type in the fixture: $t")
    }

    /** What our parser makes of a pinned line: a state, stats, or null for "ignored whole". */
    private fun decoded(line: String): Any? = when (val msg = PcLinkProtocol.parseControlLine(line)) {
        is PcControlMessage.Depth -> msg.state
        is PcControlMessage.Stats -> msg.stats
        PcControlMessage.Unknown -> null
        null -> throw AssertionError("a pinned line is malformed JSON to our parser: $line")
        else -> throw AssertionError("a pinned line parsed as something else: $msg")
    }

    private val codecs = listOf(PcCodecCapability("video/hevc", 3840, 1080, 60))

    // -----------------------------------------------------------------------------------------
    // wire — the bytes
    // -----------------------------------------------------------------------------------------

    /**
     * Every `set_depth` line, byte for byte. This is the assertion that justifies building the
     * line by hand instead of through [JSONObject]: field order and the absence of every field the
     * request does not carry are fixed by the fixture, and `org.json` guarantees neither.
     */
    @Test
    fun `every set_depth wire vector encodes byte for byte`() {
        val vectors = section("wire").filter { it.getString("direction") == "client->server" }
        assertTrue("the fixture should carry client->server wire vectors", vectors.isNotEmpty())
        for (v in vectors) {
            assertEquals(
                "wire vector '${v.getString("name")}'",
                v.getString("line"),
                PcLinkDepthProtocol.setDepthLine(request(v.getJSONObject("message")))
            )
        }
    }

    /** Every `depth` and `stats` line the server pins is read back as the message it pins. */
    @Test
    fun `every depth and stats wire vector decodes to the pinned message`() {
        val vectors = section("wire").filter { it.getString("direction") == "server->client" }
        assertTrue("the fixture should carry server->client wire vectors", vectors.isNotEmpty())
        for (v in vectors) {
            assertEquals(
                "wire vector '${v.getString("name")}'",
                expected(v.getJSONObject("message")),
                decoded(v.getString("line"))
            )
        }
    }

    // -----------------------------------------------------------------------------------------
    // decode — what is kept, what is ignored whole
    // -----------------------------------------------------------------------------------------

    @Test
    fun `every decode vector is kept as pinned or ignored whole`() {
        val vectors = section("decode")
        assertTrue("the fixture should carry decode vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val want = if (v.isNull("message")) null else expected(v.getJSONObject("message"))
            assertEquals("decode vector '${v.getString("name")}'", want, decoded(v.getString("line")))
        }
    }

    /**
     * An ignored `depth` or `stats` is §2's "junk in a known type" — the message is dropped and the
     * session continues — and never the malformed-JSON protocol error that lets a receiver drop the
     * connection. The parser spells the two differently ([PcControlMessage.Unknown] versus null),
     * and a desktop must not fall off the glasses because a server formatted one number as text.
     */
    @Test
    fun `a dropped depth or stats is ignored, never a protocol error`() {
        val dropped = section("decode").filter { it.isNull("message") }
        assertTrue("the fixture pins messages to drop", dropped.isNotEmpty())
        for (v in dropped) {
            assertEquals(
                "'${v.getString("name")}' is ignored whole, not fatal",
                PcControlMessage.Unknown,
                PcLinkProtocol.parseControlLine(v.getString("line"))
            )
        }
    }

    // -----------------------------------------------------------------------------------------
    // apply — the server's policy, and the two edges of it that are ours
    // -----------------------------------------------------------------------------------------

    /**
     * The phone's sliders are drawn from `limits`, so a value they send is one the server keeps
     * as-is; and [PcDepthRange.clamp], which is what the phone uses to land a server value on a
     * slider, agrees with the server's own clamp on every pinned case. Reset lands on the fixture's
     * `defaults` — the values a `depth` carries and the phone's Reset button reads.
     */
    @Test
    fun `the phone's range agrees with the server's clamp on every apply vector`() {
        val limits = PcDepthLimits(
            divergence = range(doc.getJSONObject("limits").getJSONArray("divergence")),
            convergence = range(doc.getJSONObject("limits").getJSONArray("convergence"))
        )
        val defaults = doc.getJSONObject("defaults").let {
            PcDepthValues(it.getInt("divergence"), it.getInt("convergence"))
        }
        var checked = 0
        for (v in section("apply")) {
            if (v.isNull("after")) continue
            val name = v.getString("name")
            val m = v.getJSONObject("message")
            val before = v.getJSONObject("before")
            val after = v.getJSONObject("after")
            val want = PcDepthValues(after.getInt("divergence"), after.getInt("convergence"))
            val got = if (m.optBoolean("reset", false)) {
                defaults
            } else {
                PcDepthValues(
                    divergence = if (m.has("divergence")) limits.divergence.clamp(m.getInt("divergence"))
                    else before.getInt("divergence"),
                    convergence = if (m.has("convergence")) limits.convergence.clamp(m.getInt("convergence"))
                    else before.getInt("convergence")
                )
            }
            assertEquals("apply vector '$name'", want, got)
            checked++
        }
        assertTrue("the fixture pins applied cases", checked > 0)
    }

    /**
     * Every acknowledgement the server pins is a `depth` our parser reads, carrying the `after`
     * values — the line the phone's sliders will actually be moved by.
     */
    @Test
    fun `every pinned acknowledgement decodes to the applied values`() {
        for (v in section("apply")) {
            val name = v.getString("name")
            if (v.isNull("ack")) {
                assertTrue("'$name': a dropped message has no ack and no after", v.isNull("after"))
                continue
            }
            val ack = decoded(v.getString("ack")) as? PcDepthState
                ?: throw AssertionError("'$name': the ack must decode as a depth message")
            val after = v.getJSONObject("after")
            assertEquals("'$name' divergence", after.getInt("divergence"), ack.divergence)
            assertEquals("'$name' convergence", after.getInt("convergence"), ack.convergence)
            // The ack keeps the session's mode and whether it is converting; a reset changes neither.
            val before = v.getJSONObject("before")
            assertEquals("'$name' setting", before.getString("setting"), ack.setting)
            assertEquals("'$name' active", before.getBoolean("active"), ack.active)
        }
    }

    // -----------------------------------------------------------------------------------------
    // gate — the hint in hello
    // -----------------------------------------------------------------------------------------

    /**
     * This client asks for both, always — the `gate` vector "asks for both" is the row it lives on —
     * and spells "no" by leaving the field out, because the fixture makes `false` and absent the
     * same answer, so there is nothing a `false` could add.
     */
    @Test
    fun `hello asks for depth and stats, and spells no by absence`() {
        val on = JSONObject(PcLinkProtocol.helloLine("Pixel 8", codecs).trim())
        assertTrue(on.getBoolean("depth"))
        assertTrue(on.getBoolean("stats"))

        val off = JSONObject(PcLinkProtocol.helloLine("Pixel 8", codecs, depth = false, stats = false).trim())
        assertFalse(off.has("depth"))
        assertFalse(off.has("stats"))

        val both = section("gate").single { it.getString("name") == "asks for both" }
        assertTrue(both.getJSONObject("hello").getBoolean("depth"))
        assertTrue(both.getJSONObject("hello").getBoolean("stats"))
        assertTrue(both.getBoolean("depth_offered"))
        assertTrue(both.getBoolean("stats_sent"))

        val no = section("gate").single { it.getString("name") == "says false, which is the same as absent" }
        assertFalse(no.getBoolean("depth_offered"))
        assertFalse(no.getBoolean("stats_sent"))
        val never = section("gate").single { it.getString("name") == "a client from before this section" }
        assertFalse(never.getBoolean("depth_offered"))
        assertFalse(never.getBoolean("stats_sent"))
    }

    // -----------------------------------------------------------------------------------------
    // the sender, end to end: what a drag puts on the wire is a pinned line
    // -----------------------------------------------------------------------------------------

    /**
     * The three shapes a finger produces, drained from a real [PcLinkDepthSender] and encoded, are
     * the fixture's lines: one slider, both sliders, and a reset — the last one alone even though
     * values were waiting, because the server would ignore them and the fixture pins the bare form.
     */
    @Test
    fun `a drained sender puts the pinned bytes on the wire`() {
        val line = { name: String ->
            section("wire").single { it.getString("name") == name }.getString("line")
        }
        val sender = PcLinkDepthSender()

        sender.divergence(30)
        assertEquals(
            line("set_depth: one slider, divergence"),
            PcLinkDepthProtocol.setDepthLine(sender.drain(0L)!!)
        )

        sender.convergence(-100)
        assertEquals(
            line("set_depth: one slider, convergence"),
            PcLinkDepthProtocol.setDepthLine(sender.drain(1_000L)!!)
        )

        sender.divergence(30)
        sender.convergence(-100)
        assertEquals(
            line("set_depth: both sliders"),
            PcLinkDepthProtocol.setDepthLine(sender.drain(2_000L)!!)
        )

        sender.divergence(40)
        sender.convergence(200)
        sender.reset()
        assertEquals(
            line("set_depth: reset"),
            PcLinkDepthProtocol.setDepthLine(sender.drain(3_000L)!!)
        )
        assertNull("the values the reset made moot were dropped, not sent after it", sender.drain(4_000L))
    }

    /**
     * The fixture is the server's, unmodified.
     *
     * It lives in two repositories and there is no build step that copies it, so the only thing
     * standing between "in step" and "quietly diverged" is this assertion and the sentence in the
     * class doc above it.
     */
    @Test
    fun `the fixture is the server's, unmodified`() {
        val note = doc.getString("note")
        assertTrue(
            "the fixture should be the one gen_depth_vectors.py writes",
            note.contains("generated by docs/gen_depth_vectors.py")
        )
        assertTrue(
            "and describe sections 2.20 and 2.21",
            note.contains("2.20") && note.contains("2.21")
        )
    }
}
