package com.teleteh.xplayer2.data.network

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-implementation known-answer tests for §2.19 input passthrough.
 *
 * `src/test/resources/pclink_input_vectors.json` is a verbatim copy of
 * `xplayer-link-server/crates/xpl-proto/test-vectors/input_vectors.json` — the same bytes the Rust
 * and Swift suites consume, so no implementation can drift without the others noticing. Same
 * arrangement as [PcLinkEnvelopeVectorsTest] and the envelope vectors it drives.
 *
 * **The fixture is duplicated in two repositories on purpose and must be kept in step**: it is
 * generated by the server's `docs/gen_input_vectors.py`, and a regeneration there is only finished
 * once the copy here is refreshed. [`the fixture is the server's, unmodified`] pins the generator's
 * own description string so a copy taken from somewhere else, or edited here to make a test pass,
 * fails loudly rather than quietly diverging.
 *
 * Three sections, and this client owns different amounts of each:
 *
 * * `wire` — the exact newline-JSON of every message. Entirely ours: this is what we put on the
 *   socket, byte for byte.
 * * `mapping` — the coordinate map. The `letterbox` half is ours (turning a touch into a normalized
 *   coordinate); `absolute` and `relative` are the server's, asserted here because the two halves
 *   have to agree exactly and half a map cannot be checked on its own.
 * * `sessions` — the server's policy. Informational for a sender, but it is what lets the last two
 *   tests ask the question that actually matters: does the batching in [PcLinkInputSender] change
 *   what the PC ends up doing? It must not.
 */
class PcLinkInputVectorsTest {

    private val doc: JSONObject by lazy {
        val text = javaClass.classLoader!!
            .getResourceAsStream("pclink_input_vectors.json")!!
            .use { it.readBytes().toString(Charsets.UTF_8) }
        JSONObject(text)
    }

    private fun section(name: String): List<JSONObject> = objects(doc.getJSONArray(name))

    private fun mapping(name: String): List<JSONObject> =
        objects(doc.getJSONObject("mapping").getJSONArray(name))

    private fun objects(array: JSONArray): List<JSONObject> =
        (0 until array.length()).map { array.getJSONObject(it) }

    /** The fixture's own event objects → the events this client would have built. */
    private fun events(array: JSONArray): List<PcInputEvent> =
        (0 until array.length()).map { i ->
            val e = array.getJSONObject(i)
            when (val t = e.getString("t")) {
                "m" -> PcInputEvent.Move(e.getInt("dx"), e.getInt("dy"))
                "a" -> PcInputEvent.MoveAbs(e.getInt("x"), e.getInt("y"))
                "b" -> PcInputEvent.Button(e.getInt("b"), e.getBoolean("d"))
                "w" -> PcInputEvent.Wheel(e.getInt("dx"), e.getInt("dy"))
                "k" -> PcInputEvent.Key(e.getInt("u"), e.getBoolean("d"))
                "s" -> PcInputEvent.Text(e.getString("s"))
                else -> throw AssertionError("unknown event tag in the fixture: $t")
            }
        }

    private fun pixel(v: JSONObject, key: String): Pair<Int, Int>? {
        if (v.isNull(key)) return null
        val a = v.getJSONArray(key)
        return a.getInt(0) to a.getInt(1)
    }

    // -----------------------------------------------------------------------------------------
    // wire — the bytes
    // -----------------------------------------------------------------------------------------

    /**
     * Every pinned message, byte for byte.
     *
     * This is the assertion that justifies building these lines by hand instead of through
     * [JSONObject]: field order (`type` before `ev`, `t` before its payload) is fixed by the
     * fixture, and `org.json` guarantees none of it.
     */
    @Test
    fun `every wire vector encodes byte for byte`() {
        val vectors = section("wire")
        assertTrue("the fixture should carry wire vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val name = v.getString("name")
            val ev = events(v.getJSONObject("message").getJSONArray("ev"))
            assertEquals(
                "wire vector '$name'",
                v.getString("line") + "\n",
                PcLinkInputProtocol.inputLine(ev)
            )
        }
    }

    /**
     * The non-ASCII text vector, called out on its own because it is the one an encoder passes by
     * accident and fails in the field.
     *
     * `serde_json` and the generator both leave a `я` literal; `org.json` escapes non-ASCII into
     * `\uXXXX` in some builds, which is still valid JSON and still decodes to the same string — so
     * a server would accept it and nothing would look wrong. It would simply not be the bytes the
     * fixture pins, and the whole point of a cross-language fixture is that the bytes match.
     */
    @Test
    fun `a non-ASCII text commit stays literal on the wire`() {
        val v = section("wire").single { it.getString("name") == "a non-ASCII text commit" }
        val line = PcLinkInputProtocol.inputLine(listOf(PcInputEvent.Text("я")))
        assertEquals(v.getString("line") + "\n", line)
        assertTrue("the character itself, not an escape", line.contains("я"))
    }

    /** The characters JSON must escape, escaped the way `serde_json` escapes them — and no others. */
    @Test
    fun `text escaping matches the reference encoder`() {
        assertEquals(
            "{\"type\":\"input\",\"ev\":[{\"t\":\"s\",\"s\":\"a\\\"b\\\\c\\nd\\te\\u0001f/g\"}]}\n",
            PcLinkInputProtocol.inputLine(listOf(PcInputEvent.Text("a\"b\\c\nd\te\u0001f/g")))
        )
    }

    // -----------------------------------------------------------------------------------------
    // mapping — the coordinates
    // -----------------------------------------------------------------------------------------

    /** `mapping.absolute`: a normalized position onto the desktop pixel it names. */
    @Test
    fun `absolute coordinates land on the pinned desktop pixel`() {
        for (v in mapping("absolute")) {
            val desktop = v.getJSONObject("desktop")
            assertEquals(
                "absolute vector '${v.getString("name")}'",
                pixel(v, "pixel"),
                PcLinkInputProtocol.absToDesktop(
                    v.getInt("x"),
                    v.getInt("y"),
                    desktop.getInt("width"),
                    desktop.getInt("height")
                )
            )
        }
    }

    /**
     * The out-of-range vectors, and the client-side half of the same rule.
     *
     * The server drops such an event; this client never produces one, because
     * [PcLinkInputSender.moveAbs] refuses it at the door. Both halves are asserted together
     * because a sender that only relied on the server's drop would be one refactor away from
     * shipping coordinates that quietly do nothing.
     */
    @Test
    fun `an out of range coordinate maps nowhere and is never sent`() {
        val out = mapping("absolute").filter { it.isNull("pixel") }
        assertEquals("the fixture pins two out-of-range cases", 2, out.size)
        val sender = PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
        for (v in out) {
            val desktop = v.getJSONObject("desktop")
            assertNull(
                "'${v.getString("name")}' has no pixel",
                PcLinkInputProtocol.absToDesktop(
                    v.getInt("x"),
                    v.getInt("y"),
                    desktop.getInt("width"),
                    desktop.getInt("height")
                )
            )
            sender.moveAbs(v.getInt("x"), v.getInt("y"))
        }
        assertNull("the sender refuses to queue an out-of-range position", sender.drain())
    }

    /** `mapping.relative`: a normalized delta scaled to whole desktop pixels, truncating to zero. */
    @Test
    fun `relative deltas scale to the pinned pixel deltas`() {
        for (v in mapping("relative")) {
            val desktop = v.getJSONObject("desktop")
            val want = pixel(v, "pixel")!!
            assertEquals(
                "relative vector '${v.getString("name")}' dx",
                want.first,
                PcLinkInputProtocol.scaleDelta(v.getInt("dx"), desktop.getInt("width"))
            )
            assertEquals(
                "relative vector '${v.getString("name")}' dy",
                want.second,
                PcLinkInputProtocol.scaleDelta(v.getInt("dy"), desktop.getInt("height"))
            )
        }
    }

    /**
     * `mapping.letterbox`: **this client's own half of the map** — a raw touch in a view that is not
     * the shape of the desktop, turned into a normalized content coordinate.
     *
     * Both shapes are pinned: a 16:9 desktop in a square view (bars top and bottom) and in a wide
     * view (bars left and right), because the branch that picks which axis binds is exactly where a
     * reimplementation goes wrong.
     */
    @Test
    fun `a touch in a letterboxed view normalizes as pinned`() {
        val vectors = mapping("letterbox")
        assertTrue("the fixture should carry letterbox vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val view = v.getJSONObject("view")
            val content = v.getJSONObject("content")
            val touch = v.getJSONArray("touch")
            assertEquals(
                "letterbox vector '${v.getString("name")}'",
                pixel(v, "norm"),
                PcLinkInputProtocol.viewToContent(
                    touch.getInt(0),
                    touch.getInt(1),
                    view.getInt("width"),
                    view.getInt("height"),
                    content.getInt("width"),
                    content.getInt("height")
                )
            )
        }
    }

    /**
     * A touch on a bar is *nowhere*, and stays nowhere all the way to the wire.
     *
     * The alternative a sender reaches for — clamping to the nearest edge — is worse than doing
     * nothing: it means a stray thumb resting on the letterbox slides the cursor to the edge of
     * the desktop, which looks like the pointer running away on its own.
     */
    @Test
    fun `a touch on a letterbox bar is nowhere`() {
        val bars = mapping("letterbox").filter { it.isNull("norm") }
        assertEquals("the fixture pins three bar touches", 3, bars.size)
        for (v in bars) {
            val view = v.getJSONObject("view")
            val content = v.getJSONObject("content")
            val touch = v.getJSONArray("touch")
            assertNull(
                "'${v.getString("name")}' is on a bar",
                PcLinkInputProtocol.viewToContent(
                    touch.getInt(0),
                    touch.getInt(1),
                    view.getInt("width"),
                    view.getInt("height"),
                    content.getInt("width"),
                    content.getInt("height")
                )
            )
        }
    }

    /**
     * The two halves composed: a finger at a named point of a letterboxed view lands on a named
     * desktop pixel.
     *
     * Neither half alone proves this. `viewToContent` could be off by a scale factor and still
     * match its own vectors if `absToDesktop` were off by the inverse — which is precisely the
     * failure a phone and a server written from the same prose fall into.
     */
    @Test
    fun `a finger on the picture reaches the desktop pixel under it`() {
        // 1000x1000 view showing a 1920x1080 desktop: bars top and bottom, content 1000x562 at y=219.
        val center = PcLinkInputProtocol.viewToContent(500, 500, 1000, 1000, 1920, 1080)
        assertNotNull(center)
        assertEquals(
            960 to 540,
            PcLinkInputProtocol.absToDesktop(center!!.first, center.second, 1920, 1080)
        )
        // The very first pixel of the picture, one row below the top bar.
        val topLeft = PcLinkInputProtocol.viewToContent(0, 219, 1000, 1000, 1920, 1080)!!
        assertEquals(0 to 0, PcLinkInputProtocol.absToDesktop(topLeft.first, topLeft.second, 1920, 1080))
    }

    /**
     * An `sbs` stream is a double-width frame carrying two eyes, and a coordinate is a fraction of
     * *one* of them.
     *
     * Getting this wrong does not look like a coordinate bug: the cursor tracks at half speed and
     * cannot reach the right half of the desktop, which reads as a broken touchpad.
     */
    @Test
    fun `a stereo stream is measured one eye wide`() {
        val sbs = config(width = 3840, height = 1080, stereo = "sbs")
        val mono = config(width = 1920, height = 1080, stereo = "mono")
        assertEquals(1920, PcLinkInputProtocol.contentWidthOf(sbs))
        assertEquals(1920, PcLinkInputProtocol.contentWidthOf(mono))
    }

    // -----------------------------------------------------------------------------------------
    // sessions — what the PC actually does with what we send
    // -----------------------------------------------------------------------------------------

    /**
     * The reference policy, replayed: every `sessions` vector's steps produce the pinned actions.
     *
     * [ServerPolicy] is a test-local transcription of the server's `InputSession` — it ships in no
     * APK. It is here so the two tests after this one can be written at all: to ask whether this
     * client's batching changes what the PC does, something has to be able to say what the PC does.
     * Asserting it against the fixture first is what makes it trustworthy enough to answer with.
     */
    @Test
    fun `the reference policy reproduces every pinned session`() {
        val vectors = section("sessions")
        assertTrue("the fixture should carry session vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val desktop = v.getJSONObject("desktop")
            val policy = ServerPolicy(
                encryption = v.getInt("encryption"),
                enabled = v.getBoolean("enabled"),
                width = desktop.getInt("width"),
                height = desktop.getInt("height")
            )
            for (step in objects(v.getJSONArray("steps"))) {
                if (step.has("teardown")) {
                    policy.teardown()
                } else {
                    policy.feed(events(step.getJSONObject("input").getJSONArray("ev")))
                }
            }
            assertEquals(
                "session vector '${v.getString("name")}'",
                v.getJSONArray("actions").toString(),
                JSONArray(policy.actions).toString()
            )
        }
    }

    /**
     * **The question this client actually has to answer**: does coalescing change what the PC does?
     *
     * Every session vector's events are fed to a real [PcLinkInputSender] one at a time, as the UI
     * feeds it, drained into batches as the control writer drains it, and the batches replayed
     * through the reference policy. The result must equal what the policy does with the raw,
     * unbatched events. If it does not, this client's idea of "the same gestures, fewer messages"
     * is wrong, and the wrongness would show up on someone's desktop as a click that landed in the
     * wrong place.
     *
     * The over-cap vector is excluded and gets its own test: there, batching deliberately *does*
     * change the outcome, and for the better.
     */
    @Test
    fun `batching does not change what the PC does`() {
        val vectors = section("sessions").filter { it.getString("name") != OVER_CAP }
        assertEquals("every session vector but the over-cap one", 7, vectors.size)
        for (v in vectors) {
            val desktop = v.getJSONObject("desktop")
            val width = desktop.getInt("width")
            val height = desktop.getInt("height")
            val encryption = v.getInt("encryption")
            val enabled = v.getBoolean("enabled")

            val direct = ServerPolicy(encryption, enabled, width, height)
            val batched = ServerPolicy(encryption, enabled, width, height)
            // The sender only exists on a session that was granted input; a session without one
            // sends nothing at all, which is the encryption gate expressed as an absence.
            val sender = if (encryption >= 2 && enabled) {
                PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
            } else {
                null
            }

            for (step in objects(v.getJSONArray("steps"))) {
                if (step.has("teardown")) {
                    direct.teardown()
                    batched.teardown()
                    continue
                }
                val ev = events(step.getJSONObject("input").getJSONArray("ev"))
                direct.feed(ev)
                if (sender == null) continue
                for (e in ev) offer(sender, e)
                while (true) {
                    val batch = sender.drain() ?: break
                    assertTrue(
                        "a batch this client emits is never over the cap",
                        batch.size <= PcLinkInputProtocol.EVENT_CAP
                    )
                    batched.feed(batch)
                }
            }
            assertEquals(
                "session vector '${v.getString("name")}' survives batching",
                JSONArray(direct.actions).toString(),
                JSONArray(batched.actions).toString()
            )
        }
    }

    /**
     * The one place batching changes the outcome, and the reason the sender splits rather than
     * emitting what it was given.
     *
     * A 513-event burst is a content error the server drops **whole** — every one of those moves is
     * lost. Split at the cap, all 513 arrive in order. So here the batched run does more than the
     * direct one, and that is the point.
     */
    @Test
    fun `an over-cap burst is split rather than dropped`() {
        val v = section("sessions").single { it.getString("name") == OVER_CAP }
        val desktop = v.getJSONObject("desktop")
        val raw = events(v.getJSONArray("steps").getJSONObject(0).getJSONObject("input").getJSONArray("ev"))
        assertEquals("the fixture's burst is one past the cap", PcLinkInputProtocol.EVENT_CAP + 1, raw.size)

        // Sent as-is, the server injects nothing at all: that is the pinned `actions`.
        assertEquals(0, v.getJSONArray("actions").length())

        val policy = ServerPolicy(2, true, desktop.getInt("width"), desktop.getInt("height"))
        val sender = PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
        // Coalescing collapses the burst long before the cap — 513 sequential moves are one
        // pending slot — so the split is the belt to that braces: assert the invariant directly.
        for (e in raw) offer(sender, e)
        var batches = 0
        while (true) {
            val batch = sender.drain() ?: break
            assertTrue(batch.size <= PcLinkInputProtocol.EVENT_CAP)
            policy.feed(batch)
            batches++
        }
        assertTrue("something got through", batches > 0)
        assertTrue("and the desktop moved, unlike the unbatched case", policy.actions.isNotEmpty())
    }

    /**
     * The fixture is the server's, unmodified.
     *
     * It lives in two repositories and there is no build step that copies it, so the only thing
     * standing between "in step" and "quietly diverged" is this assertion and the sentence in the
     * class doc above it.
     */
    @Test
    fun `the fixture is the server's, unmodified`() {
        val note = doc.getString("note")
        assertTrue(
            "the fixture should be the one gen_input_vectors.py writes",
            note.contains("generated by docs/gen_input_vectors.py")
        )
        assertTrue(
            "and the one every implementation reads",
            note.contains("Consumed byte-identically by the Rust, Kotlin and Swift suites")
        )
    }

    // -----------------------------------------------------------------------------------------
    // helpers
    // -----------------------------------------------------------------------------------------

    private fun offer(sender: PcLinkInputSender, e: PcInputEvent) = when (e) {
        is PcInputEvent.Move -> sender.move(e.dx, e.dy)
        is PcInputEvent.MoveAbs -> sender.moveAbs(e.x, e.y)
        is PcInputEvent.Button -> sender.button(e.b, e.d)
        is PcInputEvent.Wheel -> sender.wheel(e.dx, e.dy)
        is PcInputEvent.Key -> sender.key(e.u, e.d)
        is PcInputEvent.Text -> sender.text(e.s)
    }

    private fun config(width: Int, height: Int, stereo: String) = PcLinkStreamConfig(
        mime = "video/hevc",
        width = width,
        height = height,
        fps = 60f,
        stereo = stereo,
        canvasAngularWidthDeg = 45f,
        canvasDistanceM = 3f,
        videoToken = "00".repeat(32)
    )

    /**
     * A transcription of the reference server's `InputSession` (`xpl-input/src/lib.rs`), emitting
     * the platform-neutral actions the `sessions` fixture pins. Test-only.
     */
    private class ServerPolicy(encryption: Int, enabled: Boolean, val width: Int, val height: Int) {

        private val live = encryption >= 2 && enabled
        private var accX = 0L
        private var accY = 0L
        private val heldButtons = sortedSetOf<Int>()
        private val heldKeys = sortedSetOf<Int>()
        private var pendRel: Pair<Int, Int>? = null
        private var pendAbs: Pair<Int, Int>? = null

        val actions = ArrayList<JSONObject>()

        fun feed(ev: List<PcInputEvent>) {
            if (!live) return
            if (ev.size > PcLinkInputProtocol.EVENT_CAP) return
            for (e in ev) event(e)
            flush()
        }

        private fun event(e: PcInputEvent) {
            when (e) {
                is PcInputEvent.Move -> {
                    if (pendAbs != null) flush()
                    val (dx, dy) = pendRel ?: (0 to 0)
                    pendRel = (dx + e.dx) to (dy + e.dy)
                    return
                }
                is PcInputEvent.MoveAbs -> {
                    if (PcLinkInputProtocol.absToDesktop(e.x, e.y, width, height) == null) return
                    flush()
                    pendAbs = e.x to e.y
                    return
                }
                else -> flush()
            }
            when (e) {
                is PcInputEvent.Button -> {
                    val label = BUTTONS[e.b] ?: return
                    if (e.d) heldButtons.add(e.b) else heldButtons.remove(e.b)
                    actions.add(action("button").put("button", label).put("down", e.d))
                }
                is PcInputEvent.Wheel -> {
                    if (e.dx == 0 && e.dy == 0) return
                    actions.add(action("wheel").put("dx", e.dx).put("dy", e.dy))
                }
                is PcInputEvent.Key -> {
                    if (!PcLinkHidKeys.isInjectable(e.u)) return
                    if (e.d) heldKeys.add(e.u) else heldKeys.remove(e.u)
                    actions.add(action("key").put("usage", e.u).put("down", e.d))
                }
                is PcInputEvent.Text -> {
                    if (e.s.isEmpty()) return
                    actions.add(action("text").put("text", e.s))
                }
                is PcInputEvent.Move, is PcInputEvent.MoveAbs -> Unit // returned above
            }
        }

        private fun flush() {
            pendRel?.let { (dx, dy) ->
                accX += dx.toLong() * width
                accY += dy.toLong() * height
                val px = accX / PcLinkInputProtocol.ABS_RANGE
                val py = accY / PcLinkInputProtocol.ABS_RANGE
                accX -= px * PcLinkInputProtocol.ABS_RANGE
                accY -= py * PcLinkInputProtocol.ABS_RANGE
                if (px != 0L || py != 0L) {
                    actions.add(action("move_by").put("dx", px).put("dy", py))
                }
            }
            pendAbs?.let { (x, y) ->
                val (px, py) = PcLinkInputProtocol.absToDesktop(x, y, width, height)!!
                actions.add(action("move_to").put("x", px).put("y", py))
            }
            pendRel = null
            pendAbs = null
        }

        fun teardown() {
            for (b in heldButtons) actions.add(action("button").put("button", BUTTONS[b]).put("down", false))
            for (u in heldKeys) actions.add(action("key").put("usage", u).put("down", false))
            heldButtons.clear()
            heldKeys.clear()
        }

        private fun action(a: String) = JSONObject().put("a", a)

        companion object {
            val BUTTONS = mapOf(0 to "left", 1 to "right", 2 to "middle")
        }
    }

    companion object {
        private const val OVER_CAP = "an over-cap batch is dropped whole"
    }
}
