package com.teleteh.xplayer2.data.network

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-implementation known-answer tests for §2.19.7, the media keys.
 *
 * `src/test/resources/pclink_media_vectors.json` is a verbatim copy of
 * `xplayer-link-server/crates/xpl-proto/test-vectors/media_vectors.json` — the same bytes the Rust
 * and Swift suites consume. **Duplicated in two repositories on purpose and kept in step by hand**,
 * like the input and depth fixtures next door: regenerated by the server's
 * `docs/gen_media_vectors.py`, and finished only once the copy here is refreshed.
 *
 * What this client owns of it: the bytes of every `"c"` event (`wire`), sending them only when the
 * PC listed `"media"` (`capability`), and the two things a sender can get wrong in the `sessions`
 * — that a tap is down *and* up in one batch, and that a held media key is released on teardown
 * after the keyboard keys, ascending. The platform maps are the server's and are not asserted.
 */
class PcLinkMediaVectorsTest {

    private val doc: JSONObject by lazy {
        val text = javaClass.classLoader!!
            .getResourceAsStream("pclink_media_vectors.json")!!
            .use { it.readBytes().toString(Charsets.UTF_8) }
        JSONObject(text)
    }

    private fun section(name: String): List<JSONObject> = objects(doc.getJSONArray(name))

    private fun objects(array: JSONArray): List<JSONObject> =
        (0 until array.length()).map { array.getJSONObject(it) }

    private fun strings(array: JSONArray): List<String> =
        (0 until array.length()).map { array.getString(it) }

    /** The fixture's event objects → the events this client would have built. */
    private fun events(array: JSONArray): List<PcInputEvent> =
        (0 until array.length()).map { i ->
            val e = array.getJSONObject(i)
            when (val t = e.getString("t")) {
                "m" -> PcInputEvent.Move(e.getInt("dx"), e.getInt("dy"))
                "c" -> PcInputEvent.Media(e.getInt("u"), e.getBoolean("d"))
                else -> throw AssertionError("unexpected event tag in the media fixture: $t")
            }
        }

    /** A `config.input` whose `keys` are the fixture's — what the server granted this session. */
    private fun grant(keys: JSONArray) = PcInputOffer(
        pointer = listOf(PcLinkInputProtocol.POINTER_REL, PcLinkInputProtocol.POINTER_ABS),
        keys = strings(keys),
        wheel = true
    )

    /** Every event in a session is well-formed enough to have a client-side shape. */
    private fun wellFormed(events: JSONArray): Boolean =
        (0 until events.length()).all { events.getJSONObject(it).opt("d") is Boolean }

    // -----------------------------------------------------------------------------------------
    // wire — the bytes
    // -----------------------------------------------------------------------------------------

    /** Every pinned `input` line carrying a `"c"`, byte for byte, through the existing encoder. */
    @Test
    fun `every wire vector encodes byte for byte`() {
        val vectors = section("wire")
        assertTrue("the fixture should carry wire vectors", vectors.isNotEmpty())
        for (v in vectors) {
            assertEquals(
                "wire vector '${v.getString("name")}'",
                v.getString("line"),
                PcLinkInputProtocol.inputLine(events(v.getJSONObject("message").getJSONArray("ev")))
            )
        }
    }

    /** The injectable six are exactly the fixture's, by name and by number. */
    @Test
    fun `the injectable set is the fixture's six`() {
        val usages = doc.getJSONObject("usages")
        assertEquals(PcLinkMediaKeys.PLAY_PAUSE, usages.getInt("play_pause"))
        assertEquals(PcLinkMediaKeys.NEXT, usages.getInt("next"))
        assertEquals(PcLinkMediaKeys.PREVIOUS, usages.getInt("previous"))
        assertEquals(PcLinkMediaKeys.VOLUME_UP, usages.getInt("volume_up"))
        assertEquals(PcLinkMediaKeys.VOLUME_DOWN, usages.getInt("volume_down"))
        assertEquals(PcLinkMediaKeys.MUTE, usages.getInt("mute"))
        val pinned = usages.keys().asSequence().map { usages.getInt(it) }.toSet()
        assertEquals("nothing more and nothing less", pinned, PcLinkMediaKeys.INJECTABLE)
    }

    // -----------------------------------------------------------------------------------------
    // capability — when a "c" may be sent at all
    // -----------------------------------------------------------------------------------------

    /**
     * `"c"` goes out only if `config.input.keys` lists `"media"`. A server from before the section
     * never lists it (and would skip the event as an unknown `t` if one arrived anyway); an entry
     * this build has never heard of, next to it, changes nothing.
     */
    @Test
    fun `media is sent only when the PC listed it`() {
        val vectors = section("capability")
        assertTrue("the fixture should carry capability vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val name = v.getString("name")
            val offer = grant(v.getJSONArray("config_input_keys"))
            val want = v.getBoolean("send_media")
            assertEquals("capability vector '$name': the offer's reading", want, offer.hasMedia)
            // …and the sender acts on that reading, not on a flag of its own.
            val sender = PcLinkInputSender(offer)
            sender.mediaTap(PcLinkMediaKeys.PLAY_PAUSE)
            sender.media(PcLinkMediaKeys.VOLUME_UP, true)
            val batch = sender.drain()
            if (want) {
                assertEquals(
                    "capability vector '$name': sent",
                    listOf(
                        PcInputEvent.Media(PcLinkMediaKeys.PLAY_PAUSE, true),
                        PcInputEvent.Media(PcLinkMediaKeys.PLAY_PAUSE, false),
                        PcInputEvent.Media(PcLinkMediaKeys.VOLUME_UP, true)
                    ),
                    batch
                )
            } else {
                assertNull("capability vector '$name': nothing is sent", batch)
                assertEquals("…and nothing is remembered as held", 0, sender.heldCount())
            }
        }
    }

    /** This phone offers the keys in `hello`, which is what lets a PC's UI say it speaks them back. */
    @Test
    fun `hello offers media`() {
        val obj = JSONObject(
            PcLinkProtocol.helloLine(
                "Pixel 9 Pro", listOf(PcCodecCapability("video/hevc", 3840, 1080, 60))
            ).trim()
        )
        val keys = strings(obj.getJSONObject("input").getJSONArray("keys"))
        assertTrue(keys.contains(PcLinkInputProtocol.KEYS_MEDIA))
        // And the ones a server from before the section reads are still there, unchanged.
        assertTrue(keys.contains(PcLinkInputProtocol.KEYS_HID))
        assertTrue(keys.contains(PcLinkInputProtocol.KEYS_TEXT))
    }

    // -----------------------------------------------------------------------------------------
    // sessions — what the PC does, and what this sender does to match
    // -----------------------------------------------------------------------------------------

    /**
     * The reference policy, replayed: each session's events produce the pinned actions, including
     * the drops and the teardown releases. [ServerPolicy] is a test-local transcription of the
     * server's media handling and ships in no APK; it is here so the sender tests below can say
     * what the PC does with what they send.
     */
    @Test
    fun `the reference policy reproduces every pinned session`() {
        val vectors = section("sessions")
        assertTrue("the fixture should carry session vectors", vectors.isNotEmpty())
        for (v in vectors) {
            val policy = ServerPolicy(strings(v.getJSONArray("config_input_keys")))
            policy.feed(objects(v.getJSONArray("events")))
            if (v.getBoolean("teardown")) policy.teardown()
            assertEquals(
                "session vector '${v.getString("name")}'",
                v.getJSONArray("actions").toString(),
                JSONArray(policy.actions).toString()
            )
            val heldAfter = v.getJSONArray("held_after")
            assertEquals(
                "session vector '${v.getString("name")}' leaves nothing held",
                (0 until heldAfter.length()).map { heldAfter.getInt(it) },
                policy.heldAfter()
            )
        }
    }

    /**
     * Fed to a real [PcLinkInputSender] as the strip feeds it, every well-formed session's events
     * leave the sender in one batch, in order — and the batch does to the PC exactly what the raw
     * events do. A malformed event (a `d` that is not a boolean) has no client-side shape and is
     * the server's to drop, so those sessions are the policy's alone.
     */
    @Test
    fun `what the sender sends does what the fixture says`() {
        var replayed = 0
        for (v in section("sessions")) {
            val raw = v.getJSONArray("events")
            if (!wellFormed(raw)) continue
            val name = v.getString("name")
            val keys = strings(v.getJSONArray("config_input_keys"))
            val sender = PcLinkInputSender(grant(v.getJSONArray("config_input_keys")))
            for (e in events(raw)) sender.media((e as PcInputEvent.Media).u, e.d)

            val direct = ServerPolicy(keys).also { it.feed(objects(raw)) }
            val viaSender = ServerPolicy(keys)
            val batch = sender.drain()
            if (batch != null) {
                assertNull("'$name': one batch carries the whole session", sender.drain())
                viaSender.feed(batch.map { (it as PcInputEvent.Media).let { m -> event(m.u, m.d) } })
            }
            if (v.getBoolean("teardown")) {
                direct.teardown()
                // The sender's own letting go, drained and replayed, is the phone's half of the
                // teardown rule — it must name exactly what the server would release.
                sender.releaseAll()
                sender.drain()?.let { releases ->
                    viaSender.feedTeardown(releases.map { (it as PcInputEvent.Media).let { m -> event(m.u, m.d) } })
                }
            }
            // Injections only: a `dropped` is the server refusing an event the sender never let
            // through in the first place, so it appears on one side and not the other by design.
            assertEquals(
                "session vector '$name' survives the sender",
                JSONArray(direct.actions.filter { it.has("action") }).toString(),
                JSONArray(viaSender.actions.filter { it.has("action") }).toString()
            )
            assertEquals("'$name': nothing stays held on the phone either", 0, sender.heldCount())
            replayed++
        }
        assertTrue("most sessions are replayable", replayed >= 5)
    }

    /** A tap is down then up in one batch — the fixture's first wire vector, from a real sender. */
    @Test
    fun `a tap is one batch, down then up`() {
        val sender = PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
        sender.mediaTap(PcLinkMediaKeys.PLAY_PAUSE)
        val batch = sender.drain()
        assertEquals(
            listOf(
                PcInputEvent.Media(PcLinkMediaKeys.PLAY_PAUSE, true),
                PcInputEvent.Media(PcLinkMediaKeys.PLAY_PAUSE, false)
            ),
            batch
        )
        val pinned = section("wire").single { it.getString("name") == "a play/pause tap: down and up in one batch" }
        assertEquals(pinned.getString("line"), PcLinkInputProtocol.inputLine(batch!!))
        assertEquals("a tap holds nothing", 0, sender.heldCount())
        sender.releaseAll()
        assertNull("so teardown owes nothing", sender.drain())
    }

    /**
     * Held media keys are released on teardown **after** the keyboard keys, ascending by usage —
     * the order the fixture pins for the server, and the order this sender enqueues for the phone's
     * own letting go (a session that lives on after the remote stops sending).
     */
    @Test
    fun `held media keys release after keyboard keys, ascending`() {
        val sender = PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
        sender.key(0xE0, true) // Left Ctrl, a keyboard key
        sender.media(PcLinkMediaKeys.VOLUME_DOWN, true) // 0xEA
        sender.media(PcLinkMediaKeys.NEXT, true) // 0xB5
        assertEquals(3, sender.heldCount())
        sender.drain()
        sender.releaseAll()
        assertEquals(
            listOf(
                PcInputEvent.Key(0xE0, false),
                PcInputEvent.Media(PcLinkMediaKeys.NEXT, false),
                PcInputEvent.Media(PcLinkMediaKeys.VOLUME_DOWN, false)
            ),
            sender.drain()
        )
        // The same order the fixture pins for the server's teardown of the same two keys.
        val pinned = section("sessions").single {
            it.getString("name") == "two held keys release ascending by usage on teardown"
        }
        val releases = objects(pinned.getJSONArray("actions")).filter { it.optBoolean("teardown", false) }
        assertEquals(listOf(PcLinkMediaKeys.NEXT, PcLinkMediaKeys.VOLUME_DOWN), releases.map { it.getInt("u") })
    }

    /** A usage outside the six is refused at the door and never remembered as held. */
    @Test
    fun `a usage outside the six is never sent`() {
        val sender = PcLinkInputSender(PcLinkInputProtocol.CLIENT_OFFER)
        sender.media(183, true) // the fixture's "outside the set" usage
        sender.media(0x04, true) // a keyboard-page usage on a media event
        sender.mediaTap(183)
        assertNull(sender.drain())
        assertEquals(0, sender.heldCount())
    }

    /** The fixture is the server's, unmodified — see the class doc for why this is asserted. */
    @Test
    fun `the fixture is the server's, unmodified`() {
        val note = doc.getString("note")
        assertTrue(
            "the fixture should be the one gen_media_vectors.py writes",
            note.contains("generated by docs/gen_media_vectors.py")
        )
        assertTrue(note.contains("2.19.7"))
    }

    // -----------------------------------------------------------------------------------------
    // helpers
    // -----------------------------------------------------------------------------------------

    private fun event(u: Int, d: Boolean): JSONObject = JSONObject().put("t", "c").put("u", u).put("d", d)

    /**
     * A transcription of the reference server's media handling, emitting the actions the
     * `sessions` fixture pins. Test-only.
     */
    private class ServerPolicy(keys: List<String>) {

        private val live = keys.contains(PcLinkInputProtocol.KEYS_MEDIA)
        private val held = sortedSetOf<Int>()
        val actions = ArrayList<JSONObject>()

        fun feed(events: List<JSONObject>) {
            if (!live) return
            for (e in events) {
                val u = e.getInt("u")
                val d = e.opt("d")
                if (d !is Boolean || !PcLinkMediaKeys.isInjectable(u)) {
                    actions.add(JSONObject().put("dropped", e))
                    continue
                }
                if (d) held.add(u) else held.remove(u)
                actions.add(JSONObject().put("action", "media").put("u", u).put("d", d))
            }
        }

        fun teardown() {
            for (u in held) {
                actions.add(JSONObject().put("action", "media").put("u", u).put("d", false).put("teardown", true))
            }
            held.clear()
        }

        /**
         * For the replay through the sender: its `releaseAll` arrives as ordinary release events,
         * where the fixture marks the server's own teardown releases with `teardown: true`. Applied
         * as releases and flagged the same way, so the two transcripts compare as one.
         */
        fun feedTeardown(events: List<JSONObject>) {
            if (!live) return
            for (e in events) {
                val u = e.getInt("u")
                held.remove(u)
                actions.add(JSONObject().put("action", "media").put("u", u).put("d", false).put("teardown", true))
            }
        }

        fun heldAfter(): List<Int> = held.toList()
    }
}
